name: linux

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        compiler: [dmd, ldc, dmd-beta, ldc-beta]

    steps:
    - uses: actions/checkout@v1

    - name: test
      run: |
        source $(curl https://dlang.org/install.sh | bash -s -- ${{ matrix.compiler }} -a)
        dub test -b=unittest-cov

    - name: codecov
      if: ${{ matrix.compiler == 'dmd' }}
      run: bash <(curl -s https://codecov.io/bash)
